# Generated by Django 3.1.4 on 2021-01-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20210118_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='user',
            name='end_about_me',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='about me (end)'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_donation',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='user',
            name='total_project',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='user',
            name='total_volunteers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
    ]
