# Generated by Django 3.1.4 on 2021-01-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210118_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='title')),
                ('about', models.TextField(blank=True, max_length=100, null=True, verbose_name='about')),
                ('Date', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='title')),
                ('title_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='title_2')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user_pictures/', verbose_name='picture')),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='title')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='amount')),
            ],
        ),
    ]
