# Generated by Django 3.1.4 on 2021-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_project_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_donation',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='total donation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_project',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='total project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_volunteers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='total volunteers'),
        ),
    ]
